version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: compose/local/backend.Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./src:/backend
    ports:
      - 80:80
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:mypassword@db/db"
      API_KEY: "API_KEY"
      REDIS_URL: "redis://redis:6379"

  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data1:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "db"
    expose:
      - 5432

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  postgres_data1:
  redis_data:
